apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  labels:
    app: my-mariadb-deployment
spec:
  # A single mariadb instance
  replicas: 1
  selector:
    matchLabels:
      app: my-mariadb
  template:
    metadata:
      labels:
        app: my-mariadb
    spec:
      # Use the init container to download data to the location where the mariadb container expects it
      initContainers:
        - name: init-mariadb-db
          image: busybox
          command: [ 'sh', '-c', 'cp /config/mariadb-database.sql /docker-entrypoint-initdb.d/' ]
          volumeMounts:
            - name: mariadb-init-sql
              mountPath: /config
            - name: mariadb-initdb
              mountPath: /docker-entrypoint-initdb.d/
      # The actual mariadb database
      containers:
        - name: my-mariadb
          image: mariadb:latest
          # Set required environment variables to initialize the container
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: "mysecretpw"
            - name: MARIADB_DATABASE
              value: "motivationalspeechsdb"
          # Mount the volume that has been populated by the init container
          volumeMounts:
            - name: mariadb-persistent-storage
              mountPath: /var/lib/mysql
            - name: mariadb-initdb
              mountPath: /docker-entrypoint-initdb.d/
          ports:
            - containerPort: 3306

          startupProbe: # 60*10s -> 10 min
            tcpSocket:
              port: 3306
            failureThreshold: 60
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 3306
            periodSeconds: 10
      # Define an empty volume to be shared by the init and mariadb container
      volumes:
        - name: mariadb-init-sql
          configMap:
            name: mariadb-init-sql-configmap
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: mariadb-pvc
        - name: mariadb-initdb
          emptyDir: { }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-init-sql-configmap
data:
  mariadb-database.sql: |
    CREATE TABLE `motivanional_speeches` (
        id INT AUTO_INCREMENT PRIMARY KEY,      -- Automatisch inkrementierende ID
        input VARCHAR(255),                     -- Textfeld f체r Input
        mood VARCHAR(50),                       -- Textfeld f체r Mood (Stimmung)
        speech_proposal VARCHAR(255),           -- Textfeld f체r Textvorschlag
        audio_file LONGBLOB                     -- Audiodatei im bin채ren Format  
    );
